listening-port=3478
listening-ip=0.0.0.0
realm=vcex.local
server-name=vcex
lt-cred-mech
user=vcex:vcex-local-turn
no-cli
no-tls
no-dtls
fingerprint
stale-nonce=600
no-multicast-peers
allowed-peer-ip=10.0.0.0-10.255.255.255
allowed-peer-ip=172.16.0.0-172.31.255.255
allowed-peer-ip=192.168.0.0-192.168.255.255
allowed-peer-ip=127.0.0.1-127.255.255.255
min-port=49160
max-port=49200
